### ISSUE TITLE
Feature: Azure devops pipeline via Linux.

### ISSUE THREAD

**Issue by antonyoung** [antonyoung/postalcode#9]
**Description:**
Azure DevOps pipeline is currently using Windows as default. This has been changed now using Linux as default.  xUnit is causing errors by tests captering errors! ( all tests capture errors via xUnit are now implemented as commented code. )
See also [xUnit:issues](https://github.com/xunit/xunit/issues/2005)

**Solution:**
* Solved: Change the Azure Devops pipeline to use Linux as default. See also azure-pipelines.yml
* Add code coverage and add as badge in github.
* xUnit and catching errors ( somehow this doesn't work as it supposed to be? ) Create an Bug issue at github xUnit guru's. See also [xUnit:issues](https://github.com/xunit/xunit/issues/2005)

**Additional information:**
Currently the Azure DevOps pipeline, only builds and runs the tests, Would be nice also te create a nuget packages. And eventually deploy this nuget-package see also [Feature #12 ](https://github.com/antonyoung/postalcode/issues/12)

**Example:**
```
# .NET Core
# Build and test .NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
```
